import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { ShieldCheck, Users, CalendarDays, Trophy, Medal, Lock, LogIn, Plus, Save } from 'lucide-react';
import './style.css';

const accounts=[{email:'admin@highland.local',password:'123456',role:'admin',name:'高原管理員'},{email:'member@highland.local',password:'123456',role:'member',name:'一般會員'}];
const baseMembers=[{id:'HSC-001',name:'邱泓儒',email:'member@highland.local',level:'Marksman',squad:1,points:128,attendance:7},{id:'HSC-002',name:'錢弘晏',email:'',level:'Novice',squad:2,points:72,attendance:4},{id:'HSC-003',name:'莊祥浩',email:'',level:'Sharpshooter',squad:3,points:214,attendance:10}];
const baseEvents=[{id:'EVT-001',title:'高原隊內賽｜紙靶體驗賽',date:'2026/05/16',time:'20:00',stages:2,quota:24,status:'報名中'},{id:'EVT-002',title:'新手安全課程',date:'2026/05/23',time:'19:30',stages:0,quota:12,status:'報名中'}];
const baseRegs=[{eventId:'EVT-001',memberId:'HSC-001',name:'邱泓儒'},{eventId:'EVT-001',memberId:'HSC-002',name:'錢弘晏'}];
const baseScores=[{eventId:'EVT-001',memberId:'HSC-003',name:'莊祥浩',division:'CO2 / Open',rawTime:82.42,penalties:4},{eventId:'EVT-001',memberId:'HSC-001',name:'邱泓儒',division:'CO2 / Open',rawTime:88.77,penalties:3},{eventId:'EVT-001',memberId:'HSC-002',name:'錢弘晏',division:'GBB / Standard',rawTime:99.31,penalties:6}];
function total(s){return Number(s.rawTime||0)+Number(s.penalties||0)}
function point(rank,total){const p=rank/total; if(p<=.1)return 40; if(p<=.2)return 34; if(p<=.35)return 26; if(p<=.5)return 18; return 10}
function stat(icon,label,value){const I=icon; return <div className="card stat"><I size={22}/><div><small>{label}</small><b>{value}</b></div></div>}
function App(){const [user,setUser]=useState(null); const [tab,setTab]=useState('home'); const [members,setMembers]=useState(baseMembers); const [events,setEvents]=useState(baseEvents); const [regs,setRegs]=useState(baseRegs); const [scores,setScores]=useState(baseScores); const current=members.find(m=>m.email&&m.email===user?.email); const ranked=useMemo(()=>scores.map(s=>({...s,score:total(s)})).sort((a,b)=>a.score-b.score).map((s,i,a)=>({...s,rank:i+1,levelPoint:point(i+1,a.length)})),[scores]);
if(!user)return <Login setUser={setUser}/>;
function reg(e){if(!current)return alert('這個帳號尚未綁定會員資料'); if(regs.some(r=>r.eventId===e.id&&r.memberId===current.id))return; setRegs([...regs,{eventId:e.id,memberId:current.id,name:current.name}])}
return <div className="page"><header><div><small>Highland Shooting Club</small><h1>高原射擊俱樂部</h1><p>{user.name}｜{user.role==='admin'?'管理員':'會員'}</p></div><button className="icon" onClick={()=>setUser(null)}><ShieldCheck/></button></header><nav>{['home','events','results','levels','admin','deploy'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'on':''}>{({home:'首頁',events:'活動',results:'成績',levels:'分級',admin:'管理',deploy:'上線'})[t]}</button>)}</nav><main>{tab==='home'&&<><section className="grid">{stat(Users,'會員',members.length)}{stat(CalendarDays,'活動',events.length)}{stat(Trophy,'成績',ranked.length)}{stat(Medal,'權限',user.role)}</section><h2>即時排行榜</h2><Rank ranked={ranked}/></>}{tab==='events'&&<><h2>活動報名</h2>{events.map(e=><Event key={e.id} e={e} regs={regs} onReg={()=>reg(e)}/>)}</>}{tab==='results'&&<><h2>自動排名結果</h2><Rank ranked={ranked}/><h2>會員戰績</h2>{members.map(m=><div className="card row" key={m.id}><div><b>{m.name}</b><p>{m.id}｜SQ {m.squad}｜參賽 {m.attendance} 場</p></div><div className="right"><span>{m.level}</span><b>{m.points}分</b></div></div>)}</>}{tab==='levels'&&<Levels/>}{tab==='admin'&&<Admin user={user} members={members} setMembers={setMembers} events={events} setEvents={setEvents} scores={scores} setScores={setScores}/>} {tab==='deploy'&&<Deploy/>}</main><footer><button onClick={()=>setTab(user.role==='admin'?'admin':'events')}>{user.role==='admin'?'管理員後台':'查看活動報名'}</button></footer></div>}
function Login({setUser}){const [email,setEmail]=useState('admin@highland.local'),[password,setPassword]=useState('123456'),[err,setErr]=useState('');function go(){const a=accounts.find(x=>x.email===email&&x.password===password); if(!a)return setErr('帳號或密碼錯誤'); setUser(a)} return <div className="login"><div className="loginbox"><ShieldCheck size={54}/><h1>高原射擊俱樂部</h1><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)}/><label>密碼</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<p className="err">{err}</p>}<button onClick={go}><LogIn size={16}/>登入</button><small>管理員：admin@highland.local / 123456<br/>會員：member@highland.local / 123456</small></div></div>}
function Event({e,regs,onReg}){const joined=regs.filter(r=>r.eventId===e.id).length; return <div className="card"><span>{e.status}</span><h3>{e.title}</h3><p>{e.date}｜{e.time}｜{e.stages} STAGE</p><div className="bar"><i style={{width:`${Math.min(100,joined/e.quota*100)}%`}}/></div><p>{joined}/{e.quota}人報名</p><button onClick={onReg}>我要報名</button></div>}
function Rank({ranked}){return <div className="card list">{ranked.map(r=><div className="row" key={r.eventId+r.memberId+r.rawTime}><div><b>#{r.rank} {r.name}</b><p>{r.division}｜原始 {r.rawTime}s｜罰秒 {r.penalties}s｜+{r.levelPoint}</p></div><b>{r.score.toFixed(2)}</b></div>)}</div>}
function Levels(){return <><div className="card black"><h2>分級制度核心</h2><p>不使用 Classifier，只用實際比賽紀錄升級。分數、出席、排名百分比共同判斷。</p></div>{['Novice 新手：完成2場正式紀錄賽','Marksman 射手：累積100分，進入前50%','Sharpshooter 精準射手：累積200分，進入前35%','Expert 專家：累積350分，進入前20%','Master 大師：累積550分，總排前10%'].map(x=><div className="card" key={x}>{x}</div>)}</>}
function Admin({user,members,setMembers,events,setEvents,scores,setScores}){const [name,setName]=useState(''),[title,setTitle]=useState(''),[raw,setRaw]=useState(''),[pen,setPen]=useState('0'),[mid,setMid]=useState(members[0]?.id||''),[eid,setEid]=useState(events[0]?.id||''); if(user.role!=='admin')return <div className="card center"><Lock/><h2>沒有管理員權限</h2><p>一般會員不能新增會員、活動或輸入比賽成績。</p></div>;function addM(){if(!name)return; setMembers([...members,{id:`HSC-${String(members.length+1).padStart(3,'0')}`,name,email:'',level:'Novice',squad:1,points:0,attendance:0}]); setName('')} function addE(){if(!title)return; setEvents([...events,{id:`EVT-${String(events.length+1).padStart(3,'0')}`,title,date:'2026/06/20',time:'20:00',stages:2,quota:24,status:'報名中'}]); setTitle('')} function addS(){const m=members.find(x=>x.id===mid); if(!m||!raw)return; setScores([...scores,{eventId:eid,memberId:m.id,name:m.name,division:'CO2 / Open',rawTime:Number(raw),penalties:Number(pen||0)}]); setRaw(''); setPen('0')} return <><div className="card black"><h2>管理員功能</h2><p>新增會員、建立活動、輸入秒數與罰秒，自動計算排名。</p></div><div className="card"><h3><Plus size={16}/> 新增會員</h3><input placeholder="會員姓名" value={name} onChange={e=>setName(e.target.value)}/><button onClick={addM}>新增會員</button></div><div className="card"><h3><Plus size={16}/> 新增活動</h3><input placeholder="活動名稱" value={title} onChange={e=>setTitle(e.target.value)}/><button onClick={addE}>建立活動</button></div><div className="card"><h3><Save size={16}/> 輸入比賽成績</h3><select value={eid} onChange={e=>setEid(e.target.value)}>{events.map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select><select value={mid} onChange={e=>setMid(e.target.value)}>{members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select><input type="number" placeholder="原始秒數" value={raw} onChange={e=>setRaw(e.target.value)}/><input type="number" placeholder="罰秒" value={pen} onChange={e=>setPen(e.target.value)}/><button onClick={addS}>儲存並重算排名</button></div></>}
function Deploy(){return <><div className="card black"><h2>部署網址</h2><p>這個專案可直接丟到 Vercel / Netlify 部署，手機打開網址即可使用。</p></div><div className="card"><h3>正式版提醒</h3><p>目前是前端測試版，重新整理資料會消失。正式營運需接 Supabase 資料庫與 Auth 權限。</p></div></>}

createRoot(document.getElementById('root')).render(<App/>);
